FrindlyBot_LiB/Controllers/BookModels1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrindlyBot_LiB.Data;
using FrindlyBot_LiB.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using System.Net.Mail;
using System.Net;

namespace FrindlyBot_LiB.Controllers
{
    public class BookModels1Controller : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public BookModels1Controller(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        

        // GET: BookModels1
        public async Task<IActionResult> Browse(string Title)
        {
            if (String.IsNullOrEmpty(Title))
            {
                var dataContext = _context.Books.OrderBy(c => c.Title);
                return View(await dataContext.ToListAsync());
            }
            else
            {
                var searchItems = await _context.Books.Where(s => s.Title.Contains(Title)).ToListAsync();
                return View(searchItems);


            }

        }

        
        public async Task<IActionResult> ViewBook(int id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [Authorize(Roles = "User")]
        public IActionResult MakeReservation()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "User")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MakeReservation(int id, [Bind("ReservationID,Email,StartDate,endDate,Status")] Reservations rersevations)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var username = _userManager.GetUserName(User);

            if (username == null)
            {
                return NotFound();
            }

            var book = await _context.Books
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (book == null)
            {
                return NotFound();
            }

            DateTime today = DateTime.Today;
            if (book.Quantity <= 2)
            {

                return NotFound();
            }
            else if (rersevations.StartDate < today)
            {
                return NotFound();

            }else if(rersevations.endDate < rersevations.StartDate)
            {
                return NotFound();
            }
            else
            {    
                var reservation = new Reservations()
                {
                    Email = username,
                    Status = "Pending",
                    StartDate = rersevations.StartDate,
                    endDate = rersevations.endDate,
                    BookID = id
                };

                string AdminEmail = "blessingsMwandira4@gmail.com";
                

                SendReservationConfirmationEmail(reservation.BookID , username);
                SendToAdminConfirmationEmail(reservation.Email, reservation.BookID, AdminEmail);
                TempData["ReservationSuccessMessage"] = "Book reservation made successfully!";
                book.Quantity -= 1;
                _context.Add(reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Browse));

            }


        }
        private void SendReservationConfirmationEmail(int id, string recipientEmail)
        {
            var smtpClient = new SmtpClient("smtp.gmail.com")
            {
                Port = 587,
                Credentials = new NetworkCredential("Chilegaming02@gmail.com", "edio qmmy tlmx rxoy"),
                EnableSsl = true,
            };

            var mailMessage = new MailMessage
            {
                From = new MailAddress("Chilegaming02@gmail.com"),
                Subject = "Book Reserved",
                Body = $"Reservation for Book with BookID {id} has been made Successfully.",
                IsBodyHtml = true, 
            };

            mailMessage.To.Add(recipientEmail);

            try
            {
                smtpClient.Send(mailMessage);
            }
            catch (Exception ex)
            {
     
            }
        }

        private void SendToAdminConfirmationEmail(string user,int id, string recipientEmail)
        {
            var smtpClient = new SmtpClient("smtp.gmail.com")
            {
                Port = 587,
                Credentials = new NetworkCredential("Chilegaming02@gmail.com", "edio qmmy tlmx rxoy"),
                EnableSsl = true,
            };

            var mailMessage = new MailMessage
            {
                From = new MailAddress("Chilegaming02@gmail.com"),
                Subject = "Book Reservation",
                Body = $"User {user} has successfully made a reservation of BookID = {id}",
                IsBodyHtml = true,
            };

            mailMessage.To.Add(recipientEmail);

            try
            {
                smtpClient.Send(mailMessage);
            }
            catch (Exception ex)
            {

            }
        }




        [Authorize(Roles = "User")]
        private bool BookModelExists(int id)
        {
          return (_context.Books?.Any(e => e.BookID == id)).GetValueOrDefault();
        }
    }
}

FrindlyBot_LiB/Controllers/BookModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrindlyBot_LiB.Data;
using FrindlyBot_LiB.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Net;

namespace FrindlyBot_LiB.Controllers
{
    public class BookModelsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BookModelsController(ApplicationDbContext context)
        {
            _context = context;
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
              return _context.Books != null ? 
                          View(await _context.Books.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Books'  is null.");
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var bookModel = await _context.Books
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (bookModel == null)
            {
                return NotFound();
            }

            return View(bookModel);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }



        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookModel model)
        {
            if (model.ImagePath != null && model.ImagePath.Length > 0)
            {
                var fileName = Path.GetFileName(model.ImagePath.FileName);
                var filePath = Path.Combine("wwwroot", "images", fileName);

                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await model.ImagePath.CopyToAsync(stream);
                }

          
                var uploaded = new BookModel()
                {
                    Title = model.Title,
                    Description = model.Description,
                    Quantity = model.Quantity,
                    Author = model.Author,
                    BookCover = fileName 
                };

                
                _context.Books.Add(uploaded);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(model);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var book = await _context.Books.FindAsync(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, BookModel model)
        {
            if (id != model.BookID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var existingBook = await _context.Books.FindAsync(id);

                if (existingBook == null)
                {
                    return NotFound();
                }
                existingBook.BookID = model.BookID;
                existingBook.Title = model.Title;
                existingBook.Description = model.Description;
                existingBook.Quantity = model.Quantity;
                existingBook.Author = model.Author;

            
                if (model.ImagePath != null && model.ImagePath.Length > 0)
                {
                    var fileName = Path.GetFileName(model.ImagePath.FileName);
                    var filePath = Path.Combine("wwwroot", "images", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await model.ImagePath.CopyToAsync(stream);
                    }

                   
                    existingBook.BookCover = fileName;
                    
                }

                try
                {
                    _context.Update(existingBook);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookModelExists(existingBook.BookID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }





        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            var bookModel = await _context.Books
                .FirstOrDefaultAsync(m => m.BookID == id);
            if (bookModel == null)
            {
                return NotFound();
            }

            return View(bookModel);
        }


        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Books == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Books'  is null.");
            }
            var bookModel = await _context.Books.FindAsync(id);
            if (bookModel != null)
            {
                _context.Books.Remove(bookModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookModelExists(int id)
        {
          return (_context.Books?.Any(e => e.BookID == id)).GetValueOrDefault();
        }
    }
}

FrindlyBot_LiB/Controllers/IssueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrindlyBot_LiB.Data;
using FrindlyBot_LiB.Models;
using Microsoft.AspNetCore.Identity;
using System.Net.Mail;
using System.Net;
using System.Drawing;
using Hangfire;
using Microsoft.AspNetCore.Authorization;

namespace FrindlyBot_LiB.Controllers
{
    public class IssueController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IBackgroundJobClient _backgroundJobClient;

        public IssueController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IBackgroundJobClient backgroundJobClient)
        {
            _context = context;
            _userManager = userManager;
            _backgroundJobClient = backgroundJobClient;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(string Wmail)
        {
            if (String.IsNullOrEmpty(Wmail))
            {
                var dataContext = _context.Issued.OrderBy(c => c.ReturnDate);
                return View(await dataContext.ToListAsync());
            }
            else
            {
                var searchItems = await _context.Issued.Where(s => s.Email.Contains(Wmail)).ToListAsync();
                return View(searchItems);


            }
        }





        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Return(int? id)
        {
            if (id == null || _context.Issued == null)
            {
                return NotFound();
            }
     
            var addI = await _context.Books.FindAsync(id);
            

            var issued = await _context.Issued.FirstOrDefaultAsync(m => m.IssueID == id);
            

            if (issued == null)
            {
                return NotFound();
            }

            return View(issued);
        }


        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Return")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReturnConfirmed(int id)
        {
            if (_context.Issued == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Issued'  is null.");
            }
            var issued = await _context.Issued.FindAsync(id);
            var resID = await _context.reservations.FindAsync(issued.BookId);
            var addBook = await _context.Books.FindAsync(resID.BookID);
            if (issued != null)
            {
                addBook.Quantity += 1;
                _context.Issued.Remove(issued);
            }
            SendReturnConfirmationEmail(issued.Penalty, issued.Email);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IssuedExists(int id)
        {
          return (_context.Issued?.Any(e => e.IssueID == id)).GetValueOrDefault();
        }


        public async Task<IActionResult> PersonalisedII(string email)
        {
            var username = _userManager.GetUserName(User);
            if (username == null)
            {
                return NotFound();
            }

            if (String.IsNullOrEmpty(email))
            {
                var dataContext = _context.Issued.OrderByDescending(c => c.IssueDate).Where(s => s.Email.Equals(username));
                return View(await dataContext.ToListAsync());
            }
            else
            {
                var searchItem = await _context.Issued.Where(s => s.Email.Contains(email)).ToListAsync();
                return View(searchItem);
            }
        }


        private void SendReturnConfirmationEmail(int pen, string recipientEmail)
        {
            var smtpClient = new SmtpClient("smtp.gmail.com")
            {
                Port = 587,
                Credentials = new NetworkCredential("Chilegaming02@gmail.com", "edio qmmy tlmx rxoy"),
                EnableSsl = true,
            };

            var mailMessage = new MailMessage
            {
                From = new MailAddress("Chilegaming02@gmail.com"),
                Subject = "Book Returned",
                Body = $"Book has been returned successfull with a penalty of K {pen}",
                IsBodyHtml = true,
            };

            mailMessage.To.Add(recipientEmail);

            try
            {
                smtpClient.Send(mailMessage);
            }
            catch (Exception ex)
            {

            }
        }
    }
}

FrindlyBot_LiB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FriendlyBot_LiB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrindlyBot_LiB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FriendlyBot_LiB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BookModels" asp-action="Index">Manage Books</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Manage Reservations
                                </a>
                                <ul class="dropdown-menu">
                                    
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Pending">Reserved</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Approved</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="Index">Issued</a>
                                    </li>
                                </ul>
                            </li>
                            
                        }
                        @if (!User.IsInRole("User") && !User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="BookModels1" asp-action="Browse">Browse Books</a>
                            </li>
                        }
                        
                        @if (User.IsInRole("User"))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="PersonalisedRes">Reserved</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Issue" asp-action="PersonalisedII">Borrowed</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FriendlyBot_LiB - <a asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>